#!/usr/bin/perl
# Copyright: SZABO Gergely <szg@subogero.com>
# License  : WTFPL v2 <http://www.wtfpl.net/txt/copying/>
sub help {
    print <<EOF;
Usage: redshow [-i <issue>] <url> | -h
Pretty print an issue in plain text format.
-i <issue>  Issue number when using the URL of Redmine root
<url>       URL of issue, or Redmine root when used along with -i
-h          Show this help text
EOF
    exit shift;
}

help 0 if $ARGV[0] eq '-h';
our $issue;
if ($ARGV[0] eq '-i') {
    shift;
    $issue = shift;
    $issue = '' unless $issue =~ /\d+/;
}
our $url = shift or help 1;
if ($url =~ m|issues/(\d+)$|) {
    $issue = $1;
} elsif ($issue) {
    $url =~ s|/$||;
    $url .= "/issues/$issue";
}
$url =~ s|^|http://| unless $url =~ m|^\w+://|;

open CURL, "curl $url 2>/dev/null |" or die $!;
while (<CURL>) {
    s/\r|\n//g;
    # title
    if (m|^<h2>(.+#$issue)</h2>|) {
        print "$1 - ";
    }
    if (m|<div><h3>(.+)</h3></div>|) {
        print "$1\n\n";
    }
    # Attributes
    if (m|<th class=.+>(.+)</th><td class=.+>(.+?)(</.>)?</td>|) {
        printf "%-16s %s\n", $1, $2;
    }
    # Description
    our $desc;
    unless ($desc) {
        if (m|<p><strong>Description</strong></p>|) {
            $desc = "\nDescription\n";
        }
    } elsif (m|^</div>|) {
        print "$desc\n";
        $desc = '';
    } else {
        s|^\s*||;
        s|<br.*?>|\n|g;
        s|<.+?>||g;
        next if /^\s*$/;
        $desc .= "$_\n";
    }
    # Commits
    if (m|<h3>(Associated revisions)</h3>|) {
        print "$1\n\n";
    }
    our $commit;
    unless ($commit) {
        if (m|<p><a href=.+>Revision (.+)</a>|) {
            $commit = "$1 ";
        }
    } elsif (m|<a href="/redmine/users/\d+">(.+)</a>.+title="(.+)">|) {
        $commit .= "by $1 on $2\n";
    } elsif (m|<p>(.+?)(<.+)?</p>|) {
        $commit .= "$1\n";
        print "$commit\n";
        $commit = '';
    }
    # Updates
    if (m|<h3>(History)</h3>|) {
        print "$1\n\n";
    }
    our $hist;
    unless ($hist) {
        if (m|Updated by <a.+?>(.+?)</a>.+title="(.+)">|) {
            $hist = "Updated by $1 on $2\n";
        }
    } elsif (m|^\s*</div>$|) {
        print "$hist\n";
        $hist = '';
    } else {
        s|^\s*||;
        s|<br.*?>|\n|g;
        s|<.+?>||g;
        next if /^\s*$/;
        $hist .= "$_\n";
    }
}
